"""
SEBI Compliance Logger — immutable audit trail for all AI-generated recommendations.

Enforces:
1. SHA-256 hash of executive summary → non-repudiation
2. Mandatory SEBI disclaimer appended to every log entry
3. Append-only storage (enforced at DB layer via SQL trigger)
4. Export capability for regulatory queries

SEBI disclaimer text: standard boilerplate required for AI-generated financial content.
"""

from __future__ import annotations

import hashlib
import logging

logger = logging.getLogger(__name__)

_SEBI_DISCLAIMER = (
    "This analysis is generated by an AI system (Aletheia) and is intended solely for "
    "informational and educational purposes. It does not constitute investment advice, "
    "a solicitation to buy or sell securities, or a recommendation of any specific "
    "investment. AI-generated analysis may be inaccurate, incomplete, or outdated. "
    "Past performance of any security or investment strategy is not indicative of future "
    "results. All investment decisions involve risk, including the possible loss of "
    "principal. Consult a SEBI-registered investment adviser (RIA) before making any "
    "investment decisions. The AI system operator is not a SEBI-registered entity and "
    "this output does not constitute regulated financial advice."
)


class SEBIComplianceLogger:
    """
    Writes immutable compliance log entries to SQLite.
    The underlying table has ON UPDATE / ON DELETE triggers that raise errors,
    enforcing append-only semantics at the DB engine level.
    """

    def __init__(self, store) -> None:
        """
        Args:
            store: SQLiteStore instance (provides log_compliance() method)
        """
        self._store = store

    def log_run(
        self,
        run_id: str,
        recommendations: list,
        executive_summary: str,
    ) -> list[str]:
        """
        Log one entry per recommendation in a run.
        Returns: list of log_ids created.
        """
        log_ids: list[str] = []
        reasoning_hash = self._hash(executive_summary)

        for rec in recommendations:
            try:
                symbol = getattr(rec, "symbol", "UNKNOWN")
                action = getattr(rec, "action", "HOLD")
                confidence = float(getattr(rec, "confidence", 0.0))

                log_id = self._store.log_compliance(
                    run_id=run_id,
                    symbol=symbol,
                    action=str(action),
                    confidence=confidence,
                    reasoning_hash=reasoning_hash,
                    disclaimer=_SEBI_DISCLAIMER,
                )
                log_ids.append(log_id)
                logger.debug(
                    "SEBI compliance logged: run=%s symbol=%s action=%s log_id=%s",
                    run_id,
                    symbol,
                    action,
                    log_id,
                )
            except Exception as exc:
                logger.error("SEBIComplianceLogger: failed to log rec for run %s: %s", run_id, exc)

        return log_ids

    def export(
        self,
        from_date: str | None = None,
        to_date: str | None = None,
        limit: int = 100,
    ) -> list[dict]:
        """
        Export compliance log entries for audit queries.

        Args:
            from_date: ISO date string "YYYY-MM-DD" (inclusive)
            to_date:   ISO date string "YYYY-MM-DD" (inclusive)
            limit:     Max records to return

        Returns:
            list of dicts with: log_id, run_id, symbol, action, confidence,
                                reasoning_hash, disclaimer, logged_at
        """
        return self._store.get_compliance_log(
            from_date=from_date,
            to_date=to_date,
            limit=limit,
        )

    def verify_entry(self, log_entry: dict, original_summary: str) -> bool:
        """
        Verify that a log entry's reasoning_hash matches the given summary text.
        Used for audit integrity checks.
        """
        expected_hash = self._hash(original_summary)
        return log_entry.get("reasoning_hash") == expected_hash

    def verify_chain(self) -> dict:
        """
        Verify the compliance log's hash chain end-to-end: recomputes every
        entry's hash from its stored fields and checks the prev_hash linkage,
        catching tampering that bypasses the append-only DB triggers (e.g. a
        raw file edit). See SQLiteStore.verify_compliance_chain().
        """
        return self._store.verify_compliance_chain()

    @staticmethod
    def _hash(text: str) -> str:
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    @property
    def disclaimer_text(self) -> str:
        return _SEBI_DISCLAIMER
